// <auto-generated />
using ComicsViewer.Common.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ComicsViewer.Common.Migrations
{
    [DbContext(typeof(ComicDbContext))]
    partial class ComicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComicsViewer.Common.Resources.Comic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastSync");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("ComicsViewer.Common.Resources.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ComicId");

                    b.Property<string>("IssueNumber");

                    b.HasKey("Id");

                    b.HasIndex("ComicId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("ComicsViewer.Common.Resources.IssuePicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IssueId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssuePicture");
                });

            modelBuilder.Entity("ComicsViewer.Common.Resources.Issue", b =>
                {
                    b.HasOne("ComicsViewer.Common.Resources.Comic", "Comic")
                        .WithMany("Issues")
                        .HasForeignKey("ComicId");
                });

            modelBuilder.Entity("ComicsViewer.Common.Resources.IssuePicture", b =>
                {
                    b.HasOne("ComicsViewer.Common.Resources.Issue", "Issue")
                        .WithMany("IssuePictureLinks")
                        .HasForeignKey("IssueId");
                });
#pragma warning restore 612, 618
        }
    }
}
